### ISSUE TITLE
Mention CockroachDB on the homepage

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_web#36]
We say we support Postgres and SQLite - need to update it to also mention CockroachDB.

https://github.com/piccolo-orm/piccolo_web/blob/ccb34838f0309e9a7a26fddd3debaa70c5e0c8f0/src/pages/Index.vue#L93

**Comment by anmol111pal** [comment]
Hey, I have fixed the issue.
@dantownsend
